name: Update Oil Prices

on:
  schedule:
    # 每天早上 8 點和下午 6 點執行 (UTC+0 時間，對應台灣時間約為早上 16 點和凌晨 2 點)
    - cron: '0 0,8,16 * * *'
  workflow_dispatch:  # 允許手動觸發工作流程

# 添加明確的權限設置
permissions:
  contents: write  # 這給予工作流程對儲存庫內容的寫入權限

jobs:
  update-prices:
    runs-on: ubuntu-latest
    
    steps:
      - name: 檢出儲存庫
        uses: actions/checkout@v2
        
      - name: 設置 Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          
      - name: 安裝相依套件
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 pytz
          
      - name: 確保 data 資料夾存在
        run: |
          mkdir -p data
          touch data/.gitkeep
          
      - name: 執行爬蟲更新油價
        run: |
          python scripts/fetch_oil_prices.py
          
      - name: 檢查油價檔案是否存在並提交更新
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          # 先檢查 data 資料夾是否已被追蹤
          git add data/.gitkeep
          
          # 檢查油價檔案是否存在
          if [ -f "data/oil_prices.json" ]; then
            git add data/oil_prices.json
            
            # 檢查是否有變更需要提交
            if git diff --staged --quiet; then
              echo "沒有變更需要提交"
            else
              git commit -m "自動更新油價資料 $(date +'%Y-%m-%d %H:%M:%S')"
              
              # 直接使用內建的 GITHUB_TOKEN 推送變更
              git push
            fi
          else
            echo "油價檔案不存在，可能爬蟲執行失敗"
            exit 1
          fi
