name: Update Oil Prices

on:
  schedule:
    # 每6小時執行一次 (0, 6, 12, 18)
    - cron: '0 */6 * * *'
  workflow_dispatch:  # 允許手動觸發

jobs:
  update-oil-prices:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4
      
      - name: Run scraper
        run: |
          python scrape_oil_prices.py
      
      - name: Commit and push if changed
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "更新油價資料 - 自動更新"
          file_pattern: oil_prices.json
